# Generated by Django 3.0.7 on 2022-03-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_funds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funds',
        ),
    ]
